version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: alex80d/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    restart: always
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --error-logfile /app/gunicorn-error.log --log-level debug --capture-output
      "

  nginx:
    image: nginx:1.19.3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles/
      - media:/media/
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
